### PR TITLE
Stripped OverlayLayers

### PR DESCRIPTION
**Pull request by millionart**
- [x] Decoupled ALS_AnimBP logic blueprint from the animation blueprint
Now ALS_AnimBP will contain only the logic function, and ALS_Base_AnimBP will contain only the animation Graph, which is also the parent class of ALS_AnimBP.
- [x] Separated Overlay States into multiple sub-animation blueprints
Separated OverlayLayer from Animation Blueprint using Link Anim Layer to allow modular increase and decrease of Overlay States, added ALS_Sample to allow for subsequent transfer of sample functionality from the original.

No changes have been made to the Replicate function

### CODE REVIEW

**Review by millionart — COMMENTED** [review]
> Modified the function categories of two functions to address the problem preventing overrides in child blueprints.

**Modified description:**

> Modified two function category names to resolve the issue where overrides were not possible in child blueprints.

**Comment by millionart** [comment]
I noticed that this pull was rebased after merge, can you tell me what happened? Is there something I need to change?

**Comment by nathancmiguel** [comment]
> I noticed that this pull was rebased after merge, can you tell me what happened? Is there something I need to change?

Sorry, I did some testing on your pull request. Some blueprints were without a base class (none class) and were giving compilation errors.

**Comment by millionart** [comment]
> > I noticed that this pull was rebased after merge, can you tell me what happened? Is there something I need to change?
> 
> Sorry, I did some testing on your pull request. Some blueprints were without a base class (none class) and were giving compilation errors.

I submitted the pull after careful testing, I'm guessing maybe we're using different engine versions, can you tell me your version?

**Comment by nathancmiguel** [comment]
> > > I noticed that this pull was rebased after merge, can you tell me what happened? Is there something I need to change?
> > 
> > Sorry, I did some testing on your pull request. Some blueprints were without a base class (none class) and were giving compilation errors.
> 
> I submitted the pull after careful testing, I'm guessing maybe we're using different engine versions, can you tell me your version?

Unreal 5.1

**Pull request merged**
